#! /bin/bash

open_files=$(find /proc/$$/fd -exec readlink {} \+)

count_fd () {
    echo "$open_files" | FILE="$(readlink /proc/$$/fd/$1)" awk 'BEGIN {count = 0} $0 == ENVIRON["FILE"] {count++} END {print count}'
}

# count only reopened stdin/stdout and their duplicates
in_open_cnt=$(count_fd 0)
out_open_cnt=$(count_fd 1)

if [ "$in_open_cnt" != 1 ]; then
    echo stdin fd leak detected >&2
    # see example in `first`. Something similar is possible here (if the 1st process exits only on EPIPE/SIGPIPE)
    exec sleep 2
fi

if [ "$out_open_cnt" != 1 ]; then
    echo stdin fd leak detected >&2
    kill $(grep -i ppid /proc/$$/status | cut -f 2)
    exit 1
fi

exec cat
